config/routes.rb
Studenttransport::Application.routes.draw do
 

  devise_for :admins
  

  devise_for :users

  resources :tickets
  

  resources :emails

  resources :reservations

  resources :admins

  resources :users

  resources :trips

  resources :routes

  resources :sessions

  root :to => "pages#home"

  get '/pages/my_reservations', to: 'pages#my_reservations'

  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

end

app/models/route.rb
class Route < ActiveRecord::Base

  attr_accessible :session_id, :home_point, :away_point, :price, :schedule_order

  belongs_to :session

  has_many :trips, order: "departure_date ASC"

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  
  attr_accessible :route_id, :going_away, :departure_date, :seats

  belongs_to :route

  has_many :tickets

  def fetch_price
  	self.price = self.route.price
  	self.save
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all.sort_by { |x| [x.route, x.departure_date] }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        @trip.fetch_price
        format.html { redirect_to trips_path, notice: 'Trip was successfully created.' }
        format.json { render json: trips_path, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        @trip.fetch_price
        format.html { redirect_to trips_path, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= simple_form_for(@trip) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :route_id, collection: Route.all, label_method: lambda { |route| "#{route.session.name} | #{route.home_point} - #{route.away_point}" }, include_blank: false %>
  </div>

  <div class="form-group">
    <%= f.input :going_away %>
  </div>

  <div class="form-group">
    <%= f.input :departure_date, as: :datetime, start_year: Date.today.year, end_year: Date.today.year + 4, order: [:year, :month, :day, :hour, :minute], ampm: false, minute_step: 15  %>
  </div>

  <div class="form-group">
    <%= f.input :seats %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trips/_reservation_form.html.erb
<%= simple_form_for(Question.new) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :details, label: false %>
    <%= f.select :topic, collection: ["Accounting", "Bonds", "Commodities", "Estate Planning", "ETFs (Exchange Traded Funds", "Financial Planning", "Hedge Funds", "Insurance", "Legal", "Mutual Funds", "Private Equity", "Real Estate", "Retirement", "Stocks", "Socially Responsible Investing", "Venture Capital", "Other"] %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/trips/_trip.html.erb
		<%= trip.departure_date.strftime("%A, %B %d, %I:%M %p") %>
		<%= check_box_tag 'trip_ids[]', trip.id %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Listing trips</h1>

<table>
  <tr>
    <td>Route</td>
    <td>Going Away?</td>
    <td>Departure Date/Time</td>
    <td>Seats</td>
    <td>Price</td>
  </tr>

<% @trips.each do |trip| %>
  <tr>
    <td><%= "#{trip.route.session.name} | #{trip.route.home_point} - #{trip.route.away_point}" %>
    <td><%= trip.going_away %></td>
    <td><%= trip.departure_date.strftime("%m/%d/%y %I:%M %p") %></td>
    <td><%= trip.seats %></td>
    <td><%= trip.price %></td>
    <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
    <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>