config/routes.rb
Studenttransport::Application.routes.draw do
 

  devise_for :admins
  

  devise_for :users

  resources :tickets
  

  resources :emails

  resources :reservations

  resources :admins

  resources :users

  resources :trips

  resources :routes

  resources :sessions

  root :to => "pages#home"

  get '/pages/my_reservations', to: 'pages#my_reservations'

  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/email.rb
class Email < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/pages.rb
class Pages < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :user_id, :tickets, :tickets_attributes

  belongs_to :user

  has_many :tickets, dependent: :destroy

  accepts_nested_attributes_for :tickets

  attr_accessor :stripe_card_token  

  def total_price
  	self.tickets.to_a.sum(&:price)
  end
  
end

app/models/route.rb
class Route < ActiveRecord::Base

  attr_accessible :session_id, :home_point, :away_point, :price, :schedule_order

  belongs_to :session

  has_many :trips, order: "departure_date ASC"

end

app/models/session.rb
class Session < ActiveRecord::Base
  attr_accessible :name, :opening_date, :closing_date, :cash_close_date, :cash_information, :display_order

  has_many :routes

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :user_id, :trip_id, :price, :quantity, :reservation_id, :conductor_volunteer, :conductor_status

  belongs_to :trip

  belongs_to :reservation

  belongs_to :user

  def fetch_price
  	self.price = self.trip.price.to_i
  end
  
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  
  attr_accessible :route_id, :going_away, :departure_date, :seats

  belongs_to :route

  has_many :tickets

  def fetch_price
  	self.price = self.route.price
  	self.save
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :reservations
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		@sessions = Session.all
		@routes = Route.all
		@trips = Trip.all
	end

	def my_reservations
    	@reservations = current_user.reservations.all
	end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admins.each do |admin| %>
  <tr>
    <td><%= link_to 'Show', admin %></td>
    <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
    <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
                  <a class="navbar-brand", href="/">Gambier Coach</a>
          </div>

          <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Book Tickets", root_path %></li>
              <li><%= link_to "Service Updates", "#" %></li>
              <% if current_user %>
                <li><%= link_to "My Reservations", pages_my_reservations_path %></li>
                <li><%= link_to "Logout #{current_user.email}", destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to "Sign in", new_user_session_path %>
              <% end %>
            </ul>
          </div>
        </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gambier Coach</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", "application" %>
    <%= csrf_meta_tags %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
    
      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
        <script src="../../assets/js/html5shiv.js"></script>
        <script src="../../assets/js/respond.min.js"></script>
      <![endif]-->
  </head>
  <body>

    <%= render "layouts/header" %>

    <div class="container">
    
      <% flash.each do |name, msg| %>
                
        <%= content_tag :div, msg, class: "alert alert-info", data: { dismiss: "alert" } %>

      <% end %>

  	<%= yield %>

    </div>

  </body>
</html>

app/views/pages/home.html.erb
<h4>Gambier Coach - Book Tickets</h4>

<p>
    Welcome to Gambier Coach, the original student-run transportation service at Kenyon. We have used luxury motor coaches to transport students to and from Columbus airport during breaks in the academic year for the past six years. Our buses provide students with a spacious, air conditioned ride including bathroom, extensive luggage storage and reclining seats. Tickets are $25 each.
</p>

<div class="row">
	<div class="col-md-8">

		<%= form_tag new_reservation_path, id: "reserveForm", method: :get do %>

			<%= render @sessions.sort_by(&:display_order) %>

			<%= submit_tag "Book Selected Trips >>", class: "btn btn-success btn-lg btn-block", id: "bookTrips" %>

			<p></p>

		<% end %>

	</div>
</div>

app/views/pages/my_reservations.html.erb
<h2>My reservations</h2>

<% @reservations.each do |reservation| %>
	
	<% reservation.tickets.each do |ticket| %>

		<div class="panel panel-default">
		
			<div class="panel-heading">Ticket #<%= ticket.id %>
			</div>
		
				<div class="panel-body">

					<p><%= ticket.trip.departure_date.strftime("%A, %B %d, %I:%M %p") %></p>

					<p><%= "#{ticket.trip.route.home_point} to #{ticket.trip.route.away_point}" %></p>

				</div>

			<div class="panel-footer">

		 		<%= link_to "Cancel Ticket (Full Refund)", ticket, method: :delete, data: { confirm: 'Are you sure?' } %>

			</div>

		</div>

	<% end %>

<% end %>